const menu = [
  {
    id: 1,
    title: "Pancakes",
    category: "breakfast",
    price: "100.0",
    img: "./images1/image1.jpeg",
    desc: "printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
  },
  {
    id: 2,
    title: "Dinnerrolls",
    category: "dinner",
    price: "200.0",
    img: "./images1/image2.jpeg",
    desc: "printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
  },
  {
    id: 3,
    title: "Oreo Dream",
    category: "lunch",
    price: "450.0",
    img: "./images1/image3.jpeg",
    desc: "printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
  },
  {
    id: 4,
    title: "American Classic",
    category: "dinner",
    price: "800.0",
    img: "./images1/image4.jpeg",
    desc: "printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
  },
  {
    id: 5,
    title: "Fish and Chips",
    category: "dinner",
    price: "1000.0",
    img: "./images1/image5.jpeg",
    desc: "printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
  },
  {
    id: 6,
    title: "Oatmeal with strawbery",
    category: "breakfast",
    price: "400.0",
    img: "./images1/image6.jpeg",
    desc: "printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
  },
  {
    id: 7,
    title: "Country Delight",
    category: "lunch",
    price: "100.0",
    img: "./images1/image7.jpeg",
    desc: "printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
  },
  {
    id: 8,
    title: "Club sandwich",
    category: "breakfast",
    price: "400.0",
    img: "./images1/image8.jpeg",
    desc: "printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
  },
  {
    id: 9,
    title: "Mexican noodles",
    category: "dinner",
    price: "850.0",
    img: "./images1/image9.jpeg",
    desc: "printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five",
  },
];

export default menu;
